/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: deac95a4c2b0fcc952448f5889df67c8)
interface __BaseEnv_CloudflareEnv {
	PUBLIC_ASSETS: R2Bucket;
	PRIVATE_ASSETS: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ADMIN_ACCESS_ENABLED: "false";
	ADMIN_EMAIL: "Jacobjshmol@gmail.com";
	NEXT_PUBLIC_SITE_URL: "https://yakov.shmol.cc";
	NEXT_PUBLIC_ASSET_BASE_URL: "https://assets.yakov.shmol.cc";
	NEXT_PUBLIC_IMAGE_TRANSFORM_BASE_URL: "https://yakov.shmol.cc";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_ACCESS_ENABLED" | "ADMIN_EMAIL" | "NEXT_PUBLIC_SITE_URL" | "NEXT_PUBLIC_ASSET_BASE_URL" | "NEXT_PUBLIC_IMAGE_TRANSFORM_BASE_URL">> {}
}
