/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: eb4efbc18e44e760b51689fad7891018)
interface __BaseEnv_CloudflareEnv {
	PUBLIC_ASSETS: R2Bucket;
	PRIVATE_ASSETS: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ACCESS_APP_AUD: "93f908da0bb2dcbc27e7ac3438cb22fd2f141af2ea192305dcc326c16e62b1c7";
	ACCESS_TEAM_DOMAIN: "https://calm-math-532f.cloudflareaccess.com";
	NEXT_PUBLIC_SITE_URL: "https://yakov.shmol.cc";
	NEXT_PUBLIC_ASSET_BASE_URL: "https://assets.yakov.shmol.cc";
	NEXT_PUBLIC_IMAGE_TRANSFORM_BASE_URL: "https://yakov.shmol.cc";
	ADMIN_ACCESS_ENABLED: string;
	ADMIN_RUNTIME_ENV: string;
	ADMIN_LOCAL_BYPASS: string;
	ADMIN_EMAIL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_APP_AUD" | "ACCESS_TEAM_DOMAIN" | "NEXT_PUBLIC_SITE_URL" | "NEXT_PUBLIC_ASSET_BASE_URL" | "NEXT_PUBLIC_IMAGE_TRANSFORM_BASE_URL" | "ADMIN_ACCESS_ENABLED" | "ADMIN_RUNTIME_ENV" | "ADMIN_LOCAL_BYPASS" | "ADMIN_EMAIL">> {}
}
