/// <reference types="@cloudflare/workers-types" />

import { WorkerEntrypoint } from "cloudflare:workers";

import {
  isCacheablePublicDocumentRequest,
  publicDocumentCacheControl
} from "./src/server/cloudflare/public-cache";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- Generated only during the OpenNext build.
// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare adapter.
import handler from "./.open-next/worker.js";

export class PublicFrontend extends WorkerEntrypoint<CloudflareEnv> {
  fetch(request: Request) {
    return handler.fetch(request, this.env, this.ctx);
  }
}

export default {
  fetch(request, env, ctx) {
    if (!isCacheablePublicDocumentRequest(request)) {
      return handler.fetch(request, env, ctx);
    }

    return ctx.exports.PublicFrontend.fetch(request, {
      cf: { cacheControl: publicDocumentCacheControl }
    });
  }
} satisfies ExportedHandler<CloudflareEnv>;
